# Generated by Django 5.2.8 on 2025-11-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of the agenda item', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the agenda item')),
                ('item_type', models.CharField(choices=[('internal', 'Internal Item'), ('external', 'External Item'), ('consent', 'Consent Item'), ('information', 'Information Item'), ('discussion', 'Discussion Item'), ('decision', 'Decision Item')], default='internal', help_text='Type of agenda item', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed')], default='draft', help_text='Current status in the workflow', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the agenda')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=15, help_text='Expected discussion time in minutes')),
                ('is_consent_item', models.BooleanField(default=False, help_text='Whether this is part of consent agenda')),
                ('background_info', models.TextField(blank=True, help_text='Additional background information')),
                ('attachments_url', models.URLField(blank=True, help_text='URL to related documents')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the item was submitted', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the item was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when item was last updated')),
                ('proposer', models.ForeignKey(help_text='User who proposed the item', on_delete=django.db.models.deletion.PROTECT, related_name='proposed_agenda_items', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed the item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_agenda_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agenda Item',
                'verbose_name_plural': 'Agenda Items',
                'ordering': ['meeting', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Meeting title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the meeting')),
                ('scheduled_date', models.DateTimeField(help_text='Date and time when the meeting is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('location', models.CharField(blank=True, help_text='Physical or virtual location', max_length=255)),
                ('meeting_type', models.CharField(choices=[('regular', 'Regular Meeting'), ('emergency', 'Emergency Meeting'), ('special', 'Special Meeting'), ('workshop', 'Workshop'), ('retreat', 'Retreat')], default='regular', help_text='Type of meeting', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='draft', help_text='Current status of the meeting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when meeting was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when meeting was last updated')),
                ('is_published', models.BooleanField(default=False, help_text='Whether the meeting details are published')),
                ('consent_agenda_enabled', models.BooleanField(default=False, help_text='Whether consent agenda bundling is enabled')),
                ('chairperson', models.ForeignKey(help_text='User who chairs the meeting', on_delete=django.db.models.deletion.PROTECT, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('note_taker', models.ForeignKey(blank=True, help_text='User responsible for taking minutes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_taken_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(help_text='Name of the person making the request', max_length=255)),
                ('requester_email', models.EmailField(help_text='Email of the requester', max_length=254)),
                ('requester_organization', models.CharField(blank=True, help_text='Organization the requester represents', max_length=255)),
                ('proposed_title', models.CharField(help_text='Proposed title for the agenda item', max_length=255)),
                ('proposed_description', models.TextField(help_text='Proposed description for the agenda item')),
                ('justification', models.TextField(help_text='Why this item should be on the agenda')),
                ('supporting_documents_url', models.URLField(blank=True, help_text='URL to supporting documents')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('withdrawn', 'Withdrawn')], default='pending', help_text='Current status of the request', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the review')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when request was last updated')),
                ('agenda_item', models.OneToOneField(blank=True, help_text='Created agenda item (if approved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_request', to='coreagenda.agendaitem')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(help_text='The meeting for which the item is requested', on_delete=django.db.models.deletion.CASCADE, related_name='external_requests', to='coreagenda.meeting')),
            ],
            options={
                'verbose_name': 'External Request',
                'verbose_name_plural': 'External Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('phone', 'By Phone'), ('absent', 'Absent'), ('excused', 'Excused Absence')], default='in_person', help_text='How the person attended', max_length=20)),
                ('role', models.CharField(choices=[('attendee', 'Attendee'), ('observer', 'Observer'), ('chairperson', 'Chairperson'), ('note_taker', 'Note Taker'), ('presenter', 'Presenter'), ('guest', 'Guest')], default='attendee', help_text="The person's role in the meeting", max_length=20)),
                ('present', models.BooleanField(default=True, help_text='Whether the person was present')),
                ('arrived_late', models.BooleanField(default=False, help_text='Whether the person arrived late')),
                ('left_early', models.BooleanField(default=False, help_text='Whether the person left early')),
                ('arrival_time', models.DateTimeField(blank=True, help_text='Time of arrival (if late)', null=True)),
                ('departure_time', models.DateTimeField(blank=True, help_text='Time of departure (if early)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When the attendance was recorded')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded the attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user whose attendance is being tracked', on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(help_text='The meeting this attendance record is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='coreagenda.meeting')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['meeting', 'user'],
            },
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(help_text='The meeting this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='coreagenda.meeting'),
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title of the action', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of what needs to be done')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='proposed', help_text='Current status in the workflow', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the action', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Deadline for completion', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the action was completed', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes about the completion')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this action recurs regularly')),
                ('recurrence_pattern', models.CharField(blank=True, help_text="Pattern for recurring actions (e.g., 'monthly', 'quarterly')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when action was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when action was last updated')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who assigned the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for completing the action', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_actions', to=settings.AUTH_USER_MODEL)),
                ('agenda_item', models.ForeignKey(blank=True, help_text='The agenda item that generated this action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='coreagenda.agendaitem')),
                ('meeting', models.ForeignKey(help_text='The meeting where the action was identified', on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='coreagenda.meeting')),
            ],
            options={
                'verbose_name': 'Action Item',
                'verbose_name_plural': 'Action Items',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The minute content/notes')),
                ('minute_type', models.CharField(choices=[('general', 'General Note'), ('decision', 'Decision'), ('discussion', 'Discussion Summary'), ('action', 'Action Point'), ('procedural', 'Procedural Note'), ('attendance', 'Attendance Note')], default='general', help_text='Type of minute entry', max_length=20)),
                ('is_draft', models.BooleanField(default=True, help_text='Whether the minutes are still in draft')),
                ('approved', models.BooleanField(default=False, help_text='Whether the minutes have been approved')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the minutes were approved', null=True)),
                ('section_order', models.PositiveIntegerField(default=0, help_text='Order of this minute section')),
                ('is_decision', models.BooleanField(default=False, help_text='Whether this records a decision')),
                ('decision_text', models.TextField(blank=True, help_text='Text of the decision made')),
                ('vote_count_for', models.PositiveIntegerField(blank=True, help_text='Number of votes for (if applicable)', null=True)),
                ('vote_count_against', models.PositiveIntegerField(blank=True, help_text='Number of votes against (if applicable)', null=True)),
                ('vote_count_abstain', models.PositiveIntegerField(blank=True, help_text='Number of abstentions (if applicable)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when minute was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when minute was last updated')),
                ('agenda_item', models.ForeignKey(blank=True, help_text='Specific agenda item (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='coreagenda.agendaitem')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the minutes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_approved', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(help_text='The meeting these minutes belong to', on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='coreagenda.meeting')),
                ('recorded_by', models.ForeignKey(help_text='User who recorded the minutes', on_delete=django.db.models.deletion.PROTECT, related_name='minutes_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Minute',
                'verbose_name_plural': 'Minutes',
                'ordering': ['meeting', 'section_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the presenter (required if no user)', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email of the presenter', max_length=254)),
                ('affiliation', models.CharField(blank=True, help_text='Organization or department', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary presenter')),
                ('presentation_order', models.PositiveIntegerField(default=0, help_text='Order in which presenters will present')),
                ('notes', models.TextField(blank=True, help_text='Special notes about the presenter or presentation')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when presenter was added')),
                ('agenda_item', models.ForeignKey(help_text='The agenda item being presented', on_delete=django.db.models.deletion.CASCADE, related_name='presenters', to='coreagenda.agendaitem')),
                ('user', models.ForeignKey(blank=True, help_text='The user presenting (if internal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presenter',
                'verbose_name_plural': 'Presenters',
                'ordering': ['agenda_item', 'presentation_order', '-is_primary'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['-scheduled_date'], name='coreagenda__schedul_40d930_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status'], name='coreagenda__status_e5c603_idx'),
        ),
        migrations.AddIndex(
            model_name='externalrequest',
            index=models.Index(fields=['status', '-created_at'], name='coreagenda__status_c28fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='externalrequest',
            index=models.Index(fields=['meeting'], name='coreagenda__meeting_2362e5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['meeting', 'present'], name='coreagenda__meeting_a00837_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user'], name='coreagenda__user_id_4e8e20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('meeting', 'user')},
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['meeting', 'order'], name='coreagenda__meeting_865ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['status'], name='coreagenda__status_ec3100_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['status', 'due_date'], name='coreagenda__status_7b06fc_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['assigned_to', 'status'], name='coreagenda__assigne_5f1513_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['meeting'], name='coreagenda__meeting_28838a_idx'),
        ),
        migrations.AddIndex(
            model_name='minute',
            index=models.Index(fields=['meeting', 'section_order'], name='coreagenda__meeting_caae62_idx'),
        ),
        migrations.AddIndex(
            model_name='minute',
            index=models.Index(fields=['agenda_item'], name='coreagenda__agenda__0a51d3_idx'),
        ),
        migrations.AddIndex(
            model_name='presenter',
            index=models.Index(fields=['agenda_item', 'presentation_order'], name='coreagenda__agenda__b762f6_idx'),
        ),
    ]
